### ISSUE TITLE
US 17: Steuerelemente erstellen auf der Webseite

### ISSUE THREAD

**Issue by LauritzR** [Tonycchi/AvaCall-App#7]
Als Webnutzender möchte ich, dass mir während der Videokonferenz verschiedene Steuerelemente, wie Joystick, Button und Slider, angezeigt werden, wenn ich den Roboter steuern möchte.
- Akzeptanzkriterium:
    - [x] Es werden, zusätzlich zum schon vorhandenen Joystick, ein Button und ein Slider auf der Weboberfläche angezeigt, so dass sich die Elemente nicht überschneiden und möglichst wenig von der Videokonferenz verdecken.
    - [x] Wenn die Steuerelemente betätigt werden, werden in der Konsole die Inputs als Zahlen ausgegeben. Die Werte sind: Beim Button: 0 und 1 und beim Slider: 0 bis 100.
- Geschätzter Aufwand: 8
- Tatsächlicher Aufwand: 
- Velocity:

**Comment by Tonycchi** [comment]
All control elements exist. Every elemeent has its own log when using. Need to fix Button release when pressed and not in focus anymore.
